#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-repository-metadata
Version  : 2.0.6
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.7/maven-repository-metadata-2.0.7.jar
Source3  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.7/maven-repository-metadata-2.0.7.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.jar
Source5  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.pom
Source6  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.jar
Source7  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.0/maven-repository-metadata-2.0.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.2.0/maven-repository-metadata-2.2.0.jar
Source10  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.2.0/maven-repository-metadata-2.2.0.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar
Source12  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.pom
Source13  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.jar
Source14  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.pom
Source15  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.jar
Source16  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.pom
Source17  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.6.0/maven-repository-metadata-3.6.0.jar
Source18  : https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.6.0/maven-repository-metadata-3.6.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-repository-metadata-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-repository-metadata package.
Group: Data

%description data
data components for the mvn-maven-repository-metadata package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.8
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.9
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.9
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.0
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.6.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.6.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.6.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.6.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.7/maven-repository-metadata-2.0.7.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.7/maven-repository-metadata-2.0.7.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.8/maven-repository-metadata-2.0.8.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.0/maven-repository-metadata-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.0/maven-repository-metadata-2.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.0/maven-repository-metadata-2.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.6.0/maven-repository-metadata-3.6.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-repository-metadata/3.6.0/maven-repository-metadata-3.6.0.pom
